.PHONY: generate test lint install-tools coverage

generate:
	./generate.sh

test:
	go test -v -count=1 -covermode=count -coverprofile=coverage.out ./...
	go test -v -count=1 ./testdata/generated/...

test-race:
	go test -v -race -count=1 ./...
	go test -v -race -count=1 ./testdata/generated/...

lint:
	go fmt ./...
	go vet ./...
	revive -config revive.toml -formatter friendly ./...

install-tools:
	go install github.com/mgechev/revive

coverage:
	go tool cover -func coverage.out | grep ^total
