.PHONY: generate test lint install-tools

generate:
	./generate.sh

test:
	go test -v ./...
	go test -v ./testdata/generated/...

test-race:
	go test -v -race -count=1 ./...
	go test -v -race -count=1 ./testdata/generated/...

lint:
	go fmt ./...
	go vet ./...
	revive -config revive.toml -formatter friendly ./...

install-tools:
	go install github.com/mgechev/revive
