// Code generated by fieldmask; DO NOT EDIT.

package fieldmap

type Field int

type ProviderDataFieldMap struct {
	Root Field

	Id       Field `json:"id"`
	Name     Field `json:"name"`
	Logo     Field `json:"logo"`
	ImageUrl Field `json:"imageUrl"`
}

type ProductFieldMap struct {
	Root Field

	Sku        Field                `json:"sku"`
	Provider   ProviderDataFieldMap `json:"provider"`
	Attributes AttributeFieldMap    `json:"attributes"`
	SellerIds  Field                `json:"sellerIds"`
	BrandCodes Field                `json:"brandCodes"`
	CreatedAt  Field                `json:"createdAt"`
	Quantity   Field                `json:"quantity"`
	Stocks     Field                `json:"stocks"`
}

type AttributeFieldMap struct {
	Root Field

	Id      Field          `json:"id"`
	Code    Field          `json:"code"`
	Name    Field          `json:"name"`
	Options OptionFieldMap `json:"options"`
}

type OptionFieldMap struct {
	Root Field

	Code Field `json:"code"`
	Name Field `json:"name"`
}
